### ISSUE TITLE
Behøver hjelp med dette. Forstår ikke hvorfår den ikke vil fungere

### ISSUE THREAD

**Issue by VoXelHD** [nrkno/magisk-speil#17]
C:\Users\Fredr\MagicMirror>npm start

> magicmirror@2.17.1 start C:\Users\Fredr\MagicMirror
> electron js/electron.js

[29.10.2021 17:27.43.261] [LOG]   Starting MagicMirror: v2.17.1
[29.10.2021 17:27.43.263] [LOG]   Loading config ...
[29.10.2021 17:27.43.266] [LOG]   Loading module helpers ...
[29.10.2021 17:27.43.266] [LOG]   No helper found for module: MMM-SimpleLogo.
[29.10.2021 17:27.43.271] [LOG]   Initializing new module helper ...
[29.10.2021 17:27.43.272] [LOG]   Module helper loaded: updatenotification
[29.10.2021 17:27.43.272] [LOG]   No helper found for module: clock.
[29.10.2021 17:27.43.317] [LOG]   Initializing new module helper ...
[29.10.2021 17:27.43.318] [LOG]   Module helper loaded: calendar
[29.10.2021 17:27.43.320] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- C:\Users\Fredr\MagicMirror\modules\MMM-YrNow\node_helper.js
- C:\Users\Fredr\MagicMirror\js\app.js
- C:\Users\Fredr\MagicMirror\js\electron.js
- C:\Users\Fredr\MagicMirror\node_modules\electron\dist\resources\default_app.asar\main.js
-
[29.10.2021 17:27.43.321] [LOG]   Loading module helpers ...
[29.10.2021 17:27.43.321] [LOG]   No helper found for module: MMM-SimpleLogo.
[29.10.2021 17:27.43.322] [LOG]   Initializing new module helper ...
[29.10.2021 17:27.43.322] [LOG]   Module helper loaded: updatenotification
[29.10.2021 17:27.43.322] [LOG]   No helper found for module: clock.
[29.10.2021 17:27.43.323] [LOG]   Initializing new module helper ...
[29.10.2021 17:27.43.323] [LOG]   Module helper loaded: calendar
[29.10.2021 17:27.43.324] [ERROR] App threw an error during load
[29.10.2021 17:27.43.324] [ERROR] Error: Cannot find module 'request'
Require stack:
- C:\Users\Fredr\MagicMirror\modules\MMM-YrNow\node_helper.js
- C:\Users\Fredr\MagicMirror\js\app.js
- C:\Users\Fredr\MagicMirror\js\electron.js
- C:\Users\Fredr\MagicMirror\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (C:\Users\Fredr\MagicMirror\node_modules\module-alias\index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Fredr\MagicMirror\modules\MMM-YrNow\node_helper.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[29.10.2021 17:27.43.325] [ERROR] Whoops! There was an uncaught exception...
[29.10.2021 17:27.43.327] [ERROR] Error: Cannot find module 'request'
Require stack:
- C:\Users\Fredr\MagicMirror\modules\MMM-YrNow\node_helper.js
- C:\Users\Fredr\MagicMirror\js\app.js
- C:\Users\Fredr\MagicMirror\js\electron.js
- C:\Users\Fredr\MagicMirror\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (C:\Users\Fredr\MagicMirror\node_modules\module-alias\index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Fredr\MagicMirror\modules\MMM-YrNow\node_helper.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Fredr\\MagicMirror\\modules\\MMM-YrNow\\node_helper.js',
    'C:\\Users\\Fredr\\MagicMirror\\js\\app.js',
    'C:\\Users\\Fredr\\MagicMirror\\js\\electron.js',
    'C:\\Users\\Fredr\\MagicMirror\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}
[29.10.2021 17:27.43.327] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[29.10.2021 17:27.43.328] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[29.10.2021 17:27.43.358] [LOG]   Launching application.

**Comment by neguarD** [comment]
cd MagicMirror
npm install request
